[template.environment]
  GQL_HOST = "http://cms.xstringe.shop/graphql"
  NUXT_IMAGE_DOMAINS = "https://xstringe.shop/.*"

[build]
  command = "nuxt generate"

[images]
  remote_images = ["https://xstringe.shop/.*"]
